#!/bin/bash

roslaunch task2 rins_world.launch &
sleep 1
roslaunch task2 amcl_simulation.launch &
sleep 1
roslaunch turtlebot_rviz_launchers view_navigation.launch &
sleep 1
rosrun sound_play soundplay_node.py &
